"backend: tensorflow\nclass_name: Sequential\nconfig:\n  layers:\n  - class_name:\
  \ Conv2D\n    config:\n      activation: linear\n      activity_regularizer: null\n\
  \      batch_input_shape: !!python/tuple [null, 101, 101, 3]\n      bias_constraint:\
  \ null\n      bias_initializer:\n        class_name: Zeros\n        config: {dtype:\
  \ float32}\n      bias_regularizer: null\n      data_format: channels_last\n   \
  \   dilation_rate: &id001 !!python/tuple [1, 1]\n      dtype: float32\n      filters:\
  \ 32\n      kernel_constraint: null\n      kernel_initializer:\n        class_name:\
  \ GlorotUniform\n        config: {dtype: float32, seed: null}\n      kernel_regularizer:\n\
  \        class_name: L1L2\n        config: {l1: 0.0, l2: 0.0005000000237487257}\n\
  \      kernel_size: !!python/tuple [4, 4]\n      name: conv2d\n      padding: valid\n\
  \      strides: !!python/tuple [1, 1]\n      trainable: true\n      use_bias: true\n\
  \  - class_name: Activation\n    config: {activation: tanh, dtype: float32, name:\
  \ activation, trainable: true}\n  - class_name: BatchNormalizationV1\n    config:\n\
  \      axis: [3]\n      beta_constraint: null\n      beta_initializer:\n       \
  \ class_name: Zeros\n        config: {dtype: float32}\n      beta_regularizer: null\n\
  \      center: true\n      dtype: float32\n      epsilon: 0.001\n      gamma_constraint:\
  \ null\n      gamma_initializer:\n        class_name: Ones\n        config: {dtype:\
  \ float32}\n      gamma_regularizer: null\n      momentum: 0.99\n      moving_mean_initializer:\n\
  \        class_name: Zeros\n        config: {dtype: float32}\n      moving_variance_initializer:\n\
  \        class_name: Ones\n        config: {dtype: float32}\n      name: batch_normalization_v1\n\
  \      scale: true\n      trainable: true\n  - class_name: MaxPooling2D\n    config:\n\
  \      data_format: channels_last\n      dtype: float32\n      name: max_pooling2d\n\
  \      padding: valid\n      pool_size: !!python/tuple [2, 2]\n      strides: !!python/tuple\
  \ [2, 2]\n      trainable: true\n  - class_name: Conv2D\n    config:\n      activation:\
  \ linear\n      activity_regularizer: null\n      bias_constraint: null\n      bias_initializer:\n\
  \        class_name: Zeros\n        config: {dtype: float32}\n      bias_regularizer:\
  \ null\n      data_format: channels_last\n      dilation_rate: *id001\n      dtype:\
  \ float32\n      filters: 32\n      kernel_constraint: null\n      kernel_initializer:\n\
  \        class_name: GlorotUniform\n        config: {dtype: float32, seed: null}\n\
  \      kernel_regularizer:\n        class_name: L1L2\n        config: {l1: 0.0,\
  \ l2: 0.0005000000237487257}\n      kernel_size: !!python/tuple [4, 4]\n      name:\
  \ conv2d_1\n      padding: valid\n      strides: !!python/tuple [1, 1]\n      trainable:\
  \ true\n      use_bias: true\n  - class_name: Activation\n    config: {activation:\
  \ tanh, dtype: float32, name: activation_1, trainable: true}\n  - class_name: BatchNormalizationV1\n\
  \    config:\n      axis: [3]\n      beta_constraint: null\n      beta_initializer:\n\
  \        class_name: Zeros\n        config: {dtype: float32}\n      beta_regularizer:\
  \ null\n      center: true\n      dtype: float32\n      epsilon: 0.001\n      gamma_constraint:\
  \ null\n      gamma_initializer:\n        class_name: Ones\n        config: {dtype:\
  \ float32}\n      gamma_regularizer: null\n      momentum: 0.99\n      moving_mean_initializer:\n\
  \        class_name: Zeros\n        config: {dtype: float32}\n      moving_variance_initializer:\n\
  \        class_name: Ones\n        config: {dtype: float32}\n      name: batch_normalization_v1_1\n\
  \      scale: true\n      trainable: true\n  - class_name: MaxPooling2D\n    config:\n\
  \      data_format: channels_last\n      dtype: float32\n      name: max_pooling2d_1\n\
  \      padding: valid\n      pool_size: !!python/tuple [2, 2]\n      strides: !!python/tuple\
  \ [2, 2]\n      trainable: true\n  - class_name: Conv2D\n    config:\n      activation:\
  \ linear\n      activity_regularizer: null\n      bias_constraint: null\n      bias_initializer:\n\
  \        class_name: Zeros\n        config: {dtype: float32}\n      bias_regularizer:\
  \ null\n      data_format: channels_last\n      dilation_rate: *id001\n      dtype:\
  \ float32\n      filters: 32\n      kernel_constraint: null\n      kernel_initializer:\n\
  \        class_name: GlorotUniform\n        config: {dtype: float32, seed: null}\n\
  \      kernel_regularizer:\n        class_name: L1L2\n        config: {l1: 0.0,\
  \ l2: 0.0005000000237487257}\n      kernel_size: !!python/tuple [4, 4]\n      name:\
  \ conv2d_2\n      padding: valid\n      strides: !!python/tuple [1, 1]\n      trainable:\
  \ true\n      use_bias: true\n  - class_name: Activation\n    config: {activation:\
  \ tanh, dtype: float32, name: activation_2, trainable: true}\n  - class_name: BatchNormalizationV1\n\
  \    config:\n      axis: [3]\n      beta_constraint: null\n      beta_initializer:\n\
  \        class_name: Zeros\n        config: {dtype: float32}\n      beta_regularizer:\
  \ null\n      center: true\n      dtype: float32\n      epsilon: 0.001\n      gamma_constraint:\
  \ null\n      gamma_initializer:\n        class_name: Ones\n        config: {dtype:\
  \ float32}\n      gamma_regularizer: null\n      momentum: 0.99\n      moving_mean_initializer:\n\
  \        class_name: Zeros\n        config: {dtype: float32}\n      moving_variance_initializer:\n\
  \        class_name: Ones\n        config: {dtype: float32}\n      name: batch_normalization_v1_2\n\
  \      scale: true\n      trainable: true\n  - class_name: MaxPooling2D\n    config:\n\
  \      data_format: channels_last\n      dtype: float32\n      name: max_pooling2d_2\n\
  \      padding: valid\n      pool_size: !!python/tuple [2, 2]\n      strides: !!python/tuple\
  \ [2, 2]\n      trainable: true\n  - class_name: Conv2D\n    config:\n      activation:\
  \ linear\n      activity_regularizer: null\n      bias_constraint: null\n      bias_initializer:\n\
  \        class_name: Zeros\n        config: {dtype: float32}\n      bias_regularizer:\
  \ null\n      data_format: channels_last\n      dilation_rate: *id001\n      dtype:\
  \ float32\n      filters: 32\n      kernel_constraint: null\n      kernel_initializer:\n\
  \        class_name: GlorotUniform\n        config: {dtype: float32, seed: null}\n\
  \      kernel_regularizer:\n        class_name: L1L2\n        config: {l1: 0.0,\
  \ l2: 0.0005000000237487257}\n      kernel_size: !!python/tuple [3, 3]\n      name:\
  \ conv2d_3\n      padding: valid\n      strides: !!python/tuple [1, 1]\n      trainable:\
  \ true\n      use_bias: true\n  - class_name: Activation\n    config: {activation:\
  \ tanh, dtype: float32, name: activation_3, trainable: true}\n  - class_name: BatchNormalizationV1\n\
  \    config:\n      axis: [3]\n      beta_constraint: null\n      beta_initializer:\n\
  \        class_name: Zeros\n        config: {dtype: float32}\n      beta_regularizer:\
  \ null\n      center: true\n      dtype: float32\n      epsilon: 0.001\n      gamma_constraint:\
  \ null\n      gamma_initializer:\n        class_name: Ones\n        config: {dtype:\
  \ float32}\n      gamma_regularizer: null\n      momentum: 0.99\n      moving_mean_initializer:\n\
  \        class_name: Zeros\n        config: {dtype: float32}\n      moving_variance_initializer:\n\
  \        class_name: Ones\n        config: {dtype: float32}\n      name: batch_normalization_v1_3\n\
  \      scale: true\n      trainable: true\n  - class_name: MaxPooling2D\n    config:\n\
  \      data_format: channels_last\n      dtype: float32\n      name: max_pooling2d_3\n\
  \      padding: valid\n      pool_size: !!python/tuple [2, 2]\n      strides: !!python/tuple\
  \ [2, 2]\n      trainable: true\n  - class_name: Flatten\n    config: {data_format:\
  \ channels_last, dtype: float32, name: flatten, trainable: true}\n  - class_name:\
  \ Dense\n    config:\n      activation: linear\n      activity_regularizer: null\n\
  \      bias_constraint: null\n      bias_initializer:\n        class_name: Zeros\n\
  \        config: {dtype: float32}\n      bias_regularizer: null\n      dtype: float32\n\
  \      kernel_constraint: null\n      kernel_initializer:\n        class_name: GlorotUniform\n\
  \        config: {dtype: float32, seed: null}\n      kernel_regularizer: null\n\
  \      name: dense\n      trainable: true\n      units: 200\n      use_bias: true\n\
  \  - class_name: Activation\n    config: {activation: tanh, dtype: float32, name:\
  \ activation_4, trainable: true}\n  - class_name: BatchNormalizationV1\n    config:\n\
  \      axis: [1]\n      beta_constraint: null\n      beta_initializer:\n       \
  \ class_name: Zeros\n        config: {dtype: float32}\n      beta_regularizer: null\n\
  \      center: true\n      dtype: float32\n      epsilon: 0.001\n      gamma_constraint:\
  \ null\n      gamma_initializer:\n        class_name: Ones\n        config: {dtype:\
  \ float32}\n      gamma_regularizer: null\n      momentum: 0.99\n      moving_mean_initializer:\n\
  \        class_name: Zeros\n        config: {dtype: float32}\n      moving_variance_initializer:\n\
  \        class_name: Ones\n        config: {dtype: float32}\n      name: batch_normalization_v1_4\n\
  \      scale: true\n      trainable: true\n  - class_name: Dense\n    config:\n\
  \      activation: linear\n      activity_regularizer: null\n      bias_constraint:\
  \ null\n      bias_initializer:\n        class_name: Zeros\n        config: {dtype:\
  \ float32}\n      bias_regularizer: null\n      dtype: float32\n      kernel_constraint:\
  \ null\n      kernel_initializer:\n        class_name: GlorotUniform\n        config:\
  \ {dtype: float32, seed: null}\n      kernel_regularizer: null\n      name: dense_1\n\
  \      trainable: true\n      units: 3\n      use_bias: true\n  - class_name: Activation\n\
  \    config: {activation: softmax, dtype: float32, name: activation_5, trainable:\
  \ true}\n  name: sequential\nkeras_version: 2.2.4-tf\n"
